../colors.js: rgb.txt build.py
	./build.py RGB rgb.txt >../colors.js

rgb.txt:
	# xorg colors
	# curl -o rgb.txt 'https://raw.githubusercontent.com/freedesktop/xorg-rgb/master/rgb.txt'
	# vim colors
	curl -o rgb.txt 'https://raw.githubusercontent.com/vim/vim/master/runtime/rgb.txt'
